[package]
name = "static_files"
version = "0.0.0"
workspace = "../../"
edition = "2018"
publish = false

[dependencies]
rocket = { path = "../../core/lib" }
rocket_contrib = { path = "../../contrib/lib" }
