[package]
name = "laxtop_api"
version = "0.2.0"
authors = ["Stanislav Sagan"]
edition = "2018"

[dependencies]
rocket = { version = "0.4.5", default-features = false }
diesel = { version = "1.4.5", features = ["mysql", "chrono"] }
chrono = { version = "*", features = ["serde"] }
serde = "1.0.117"
serde_derive = "1.0.117"
serde_json = "1.0.59"
rand = "0.7.3"
regex = "1.4.1"
validator = "0.11.0"
validator_derive = "0.11.0"
futures = "0.3.7"
tgbot = "0.10.0"
tokio = "0.2.22"
dotenv = "0.15.0"
reqwest = "0.10.8"
sha2 = "0.9.1"
files_to_sub_dirs = { git = "https://github.com/incker/files_to_sub_dirs", rev = "2b3ddbc" }
telegram_oauth = { git = "https://github.com/incker/telegram_oauth", rev = "4e0a0a4" }
diesel_migrations = "1.4.0"
image = "0.23.11"
geo = "0.15.0"
geo-types = "0.6.1"
base64 = "0.13.0"

[dependencies.rocket_contrib]
version = "0.4.5"
default-features = false
features = ["json", "serve", "diesel_mysql_pool"]

[profile.release]
opt-level = 3
lto = true
